<a href="https://colab.research.google.com/github/Neha-Pal/Machine_Learning-using-Python/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Time taken by process time

In [2]:
from time import process_time

Time taken by a list

In [10]:
my_list = [i for i in range(100000)]
start_time = process_time()

my_list = [i+10 for i in my_list]
end_time = process_time()

print(end_time - start_time)


0.010469773000000515


Time taken for an array

In [11]:
arr = np.array([i for i in range(100000)])
start_time = process_time()

arr += 10
end_time = process_time()

print(end_time - start_time)

0.0003752709999993442


Numpy Arrays

In [13]:
#list
list_1 = [9,80,6,45]
print(list_1)
print(type(list_1))

[9, 80, 6, 45]
<class 'list'>


In [14]:
#array
arr_1 = np.array([9,80,6,45])
print(arr_1)
print(type(arr_1))

[ 9 80  6 45]
<class 'numpy.ndarray'>


In [17]:
#creating 1 dimensional array
arr_2 = np.array([9,80,6,45])
print(arr_1)

[ 9 80  6 45]


In [18]:
arr_2.shape

(4,)

In [19]:
#2 dimensional array
arr_3 = np.array([[1,2,3],[4,5,6]])
print(arr_3)

[[1 2 3]
 [4 5 6]]


In [20]:
arr_3.shape

(2, 3)

In [21]:
arr_4 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
print(arr_4)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Initial placeholders

In [22]:
#create a numpy array of 0's
arr_5 = np.zeros((4,5))
print(arr_5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
#create a numpy array of 1's
arr_6 = np.ones((4,3))
print(arr_6)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#array of particular values
arr_7 = np.full((3,4),5)
print(arr_7)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [25]:
#create an identity matrix
arr_8 = np.eye(4)
print(arr_8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#create a numpy array with random values
arr_9 = np.random.random((4,5))
print(arr_9)

[[0.64887634 0.72922548 0.49834668 0.99226018 0.51017583]
 [0.49067014 0.23061411 0.28017481 0.77757347 0.42526115]
 [0.8464713  0.3758441  0.58837084 0.92457042 0.70813841]
 [0.02965665 0.18174749 0.60811109 0.85668586 0.94251462]]


In [28]:
#create a numpy array with random integer values
arr_10 = np.random.randint(10,100,(4,5))
print(arr_10)

[[95 23 44 16 59]
 [11 13 40 49 23]
 [97 15 49 25 34]
 [92 48 89 35 89]]


In [32]:
#array of evenly spaced values
arr_11 = np.linspace(10,40,5)
print(arr_11)

[10.  17.5 25.  32.5 40. ]


In [34]:
#convert a list to a array
list_2 = [1,2,3,4,5]
arr_12 = np.asarray(list_2)
print(arr_12)

[1 2 3 4 5]


Analyzing an array

In [35]:
arr_13 = np.random.randint(10,100,(5,5))
print(arr_13)

[[42 30 12 65 95]
 [95 53 73 60 93]
 [40 61 25 28 28]
 [44 12 43 10 41]
 [45 59 62 42 13]]


In [36]:
#Array dimension
arr_13.shape

(5, 5)

In [37]:
#no of dimensions
arr_13.ndim

2

In [38]:
#no of elements in an array
arr_13.size


25

In [39]:
#cheking the datatype of the values of the array
arr_13.dtype

dtype('int64')

Mathematical Operation

In [40]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
print(list_1 + list_2) #+ sign will concat two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print("Array_1:\n", a)
print("Array_2:\n", b)
print("Addition:\n", a+b)
print("Subtraction\n:", b-a)
print("Multiplication:\n", a*b)

Array_1:
 [[3 0 2]
 [7 1 1]
 [9 5 1]]
Array_2:
 [[17 15 16]
 [16 11 13]
 [12 15 12]]
Addition:
 [[20 15 18]
 [23 12 14]
 [21 20 13]]
Subtraction
: [[14 15 14]
 [ 9 10 12]
 [ 3 10 11]]
Multiplication:
 [[ 51   0  32]
 [112  11  13]
 [108  75  12]]


In [48]:
#Another way
np.add(a,b)

array([[20, 15, 18],
       [23, 12, 14],
       [21, 20, 13]])

In [50]:
np.subtract(b, a)

array([[14, 15, 14],
       [ 9, 10, 12],
       [ 3, 10, 11]])

In [51]:
#Array malipulation
arr_14 = np.random.randint(0,10,(2,3))
print(arr_14)
arr_14 = arr_14.reshape((3,2))
print(arr_14)

[[9 0 2]
 [0 2 2]]
[[9 0]
 [2 0]
 [2 2]]


In [52]:
#transpose
arr_15 = np.random.randint(0,10,(2,3))
print(arr_15)
arr_15 = arr_15.transpose()
print(arr_15)


[[2 4 3]
 [9 9 0]]
[[2 9]
 [4 9]
 [3 0]]
